name: Dockerfile Scan with Trivy

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh -o install.sh
          
          if [ ! -s install.sh ]; then
            echo "Error: Failed to download Trivy install script."
            exit 1
          fi

          chmod +x install.sh

          ./install.sh

          sudo mv ./bin/trivy /usr/local/bin/trivy
      - name: List directory contents
        run: ls -lh

      - name: Scan Dockerfile with Trivy
        run: |
          trivy config --debug --exit-code 1 --severity HIGH --format table .
