name: Scan Dockerfile

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dockerfile-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dockerfile scan with Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          ./trivy config --exit-code 1 --severity HIGH dockerfile
